"""Exports: the graph document rendered for other tools (design doc §16).

  json      the document itself (what the UI consumes)
  csv       one row per shipped module with params, shapes, dtype and the
            cost estimates at the given assumptions
  markdown  a model card-style summary: headline numbers, config, stacks,
            cost at T/B/dtype, the top modules by parameters
  dot       Graphviz: the module tree to the chosen depth, edges in execution order
"""

from __future__ import annotations

import csv
import io
import json
from typing import Any

from modelmap.analytics import (
    Assumptions,
    build_index,
    compute_costs,
    fmt_big,
    fmt_bytes,
    fmt_params,
    module_rows,
    summarize,
)

FORMATS = ("json", "csv", "markdown", "md", "dot")

CSV_COLUMNS = [
    "module", "kind", "class", "depth", "repeats", "multiplicity", "params",
    "params_total_with_repeats", "dtype", "weight_shapes", "input_shape", "output_shape",
    "macs_per_token", "weight_bytes", "activation_bytes", "kv_bytes_per_token", "attrs", "source",
]


def to_json(doc: dict, *, pretty: bool = False) -> str:
    return json.dumps(doc, indent=2 if pretty else None, separators=None if pretty else (",", ":"))


def to_csv(doc: dict, a: Assumptions | None = None, *, leaves_only: bool = False) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    w.writeheader()
    for row in module_rows(doc, a, leaves_only=leaves_only):
        w.writerow({k: _cell(row.get(k)) for k in CSV_COLUMNS})
    return buf.getvalue()


def _cell(v: Any) -> Any:
    if isinstance(v, float):
        return f"{v:.6g}" if abs(v) < 1e15 else f"{v:.0f}"
    return v


def to_markdown(doc: dict, a: Assumptions | None = None, *, top: int = 12) -> str:
    a = a or Assumptions()
    s = summarize(doc, a)
    index = build_index(doc)
    rep = compute_costs(doc, index, a)
    c = s["config"]
    cost = s["cost"]
    mid = s["model_id"]
    lines = [f"# {mid}", ""]
    head = [
        f"**{s['architecture'] or 'unknown architecture'}**",
        f"{fmt_params(s['params_total'] or 0)} params" + (f" ({fmt_params(s['active_params'])} active/token)" if s["active_params"] and s["params_total"] and s["active_params"] < 0.9 * s["params_total"] else ""),
        f"fidelity: {s['fidelity']}",
    ]
    if s.get("variant"):
        head.append(f"GGUF {s['variant']}")
    lines.append(" · ".join(head))
    lines.append("")
    if c:
        lines += ["## Config", "", "| key | value |", "|---|---|"]
        for k, v in c.items():
            vs = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
            if len(vs) > 80:
                vs = vs[:77] + "…"
            lines.append(f"| {k} | {vs} |")
        lines.append("")
    if s["repeat_stacks"]:
        lines += ["## Structure", ""]
        for st in s["repeat_stacks"]:
            n = index.by_id.get(st["representative"], {})
            lines.append(f"- `{st['parent']}`: ×{st['count']} {n.get('cls', '')} blocks")
        lines.append("")
    lines += [
        f"## Cost estimates (T = {a.T:,} · B = {a.B} · {a.dtype})", "",
        "| | |", "|---|---|",
        f"| compute | {fmt_big(cost['macs_per_token'], 'MAC')}/token · {fmt_big(cost['macs_per_forward'], 'MAC')} per forward |",
        f"| weights | {fmt_bytes(cost['weight_bytes'])} (stored dtypes) |",
        f"| activations | {fmt_bytes(cost['activation_bytes'])} summed · largest {fmt_bytes(cost['largest_activation_bytes'])} ({cost['largest_activation_node'] or '—'}) |",
    ]
    if cost["kv_bytes_per_token"]:
        lines.append(
            f"| KV cache | {fmt_bytes(cost['kv_bytes_per_token'])}/token · {fmt_bytes(cost['kv_bytes_at_T'])} at T ({cost['kv_layers']} layers) |"
        )
    lines.append("")
    # top modules by params (leaves and fused blocks), with multiplicity
    rows = []
    for n in doc["nodes"]:
        if not n.get("weight_shapes"):
            continue
        m = rep.multiplicity.get(n["id"], 1)
        own = sum(_prod(w) for w in n["weight_shapes"].values())
        rows.append((own * m, n, m))
    rows.sort(key=lambda r: -r[0])
    if rows:
        lines += [f"## Largest weights", "", "| module | class | shape | dtype | params (×repeats) |", "|---|---|---|---|---|"]
        for total, n, m in rows[:top]:
            shapes = " ".join(f"{k} {v}" for k, v in n["weight_shapes"].items())
            lines.append(f"| `{n['id']}` | {n['cls']} | {shapes} | {n.get('dtype') or '—'} | {fmt_params(total)}{f' (×{m})' if m > 1 else ''} |")
        lines.append("")
    if s["notes"]:
        lines += ["## Notes", ""] + [f"- {x}" for x in s["notes"]] + [""]
    lines.append(f"_Generated by modelmap · https://modelmap.cc/m/{mid}_")
    return "\n".join(lines)


def _prod(xs: list[int]) -> int:
    out = 1
    for x in xs:
        out *= x
    return out


def to_dot(doc: dict, *, depth: int = 3) -> str:
    """Graphviz digraph: clusters for containers down to `depth`, leaves as
    nodes, execution-order edges between siblings (edges touching a cluster
    use compound lhead/ltail so Graphviz draws them at the cluster border)."""
    index = build_index(doc)
    out = [
        "digraph modelmap {",
        '  rankdir=LR; compound=true; node [shape=box, fontname="Helvetica", fontsize=10]; graph [fontname="Helvetica"];',
    ]
    color = {
        "embedding": "#4E63C8", "head": "#4E63C8", "attention": "#C6537E", "mlp": "#2E8F84", "moe": "#2E8F84",
        "norm": "#8593A6", "linear": "#7C8798", "conv": "#7C8798", "container": "#AAB4C2", "module": "#AAB4C2",
    }
    clusters: set[str] = set()
    drawn: set[str] = set()

    def q(s: str) -> str:
        return '"' + s.replace('"', '\\"') + '"'

    def label(n: dict, sep: str) -> str:
        r = index.repeat_by_rep.get(n["id"])
        leaf = n["id"].rsplit(".", 1)[-1] or "model"
        return leaf + (f" ×{r['count']}" if r else "") + f"{sep}{n['cls']}" + (f"{sep}{fmt_params(n['params'])}" if n["params"] else "")

    def walk(parent: str, ind: str) -> None:
        for n in index.children.get(parent) or []:
            kids = index.children.get(n["id"]) or []
            if kids and n["depth"] < depth:
                clusters.add(n["id"])
                out.append(f"{ind}subgraph {q('cluster_' + n['id'])} {{")
                out.append(f"{ind}  label={q(label(n, ' · '))}; color={q(color.get(n['kind'], '#AAB4C2'))}; style=rounded;")
                walk(n["id"], ind + "  ")
                out.append(f"{ind}}}")
            else:
                drawn.add(n["id"])
                out.append(f"{ind}{q(n['id'] or 'model')} [label={q(label(n, chr(92) + 'n'))}, color={q(color.get(n['kind'], '#AAB4C2'))}];")

    walk("", "  ")

    def anchor(nid: str) -> str | None:
        if nid in drawn:
            return nid
        if nid in clusters:
            for k in index.children.get(nid) or []:
                a = anchor(k["id"])
                if a is not None:
                    return a
        return None

    for e in doc.get("edges") or []:
        sa, da = anchor(e["src"]), anchor(e["dst"])
        if sa is None or da is None or (e["src"] not in drawn | clusters) or (e["dst"] not in drawn | clusters):
            continue
        attrs = []
        if e.get("kind") == "aux":
            attrs.append("style=dashed")
        if e["src"] in clusters:
            attrs.append(f"ltail={q('cluster_' + e['src'])}")
        if e["dst"] in clusters:
            attrs.append(f"lhead={q('cluster_' + e['dst'])}")
        out.append(f"  {q(sa)} -> {q(da)}" + (f" [{', '.join(attrs)}]" if attrs else "") + ";")
    out.append("}")
    return "\n".join(out)


def render(doc: dict, fmt: str, a: Assumptions | None = None, **kw) -> tuple[str, str]:
    """(text, media type) for an export format."""
    fmt = fmt.lower()
    if fmt == "json":
        return to_json(doc, pretty=bool(kw.get("pretty"))), "application/json"
    if fmt == "csv":
        return to_csv(doc, a, leaves_only=bool(kw.get("leaves_only"))), "text/csv"
    if fmt in ("md", "markdown"):
        return to_markdown(doc, a), "text/markdown"
    if fmt == "dot":
        return to_dot(doc, depth=int(kw.get("depth", 3))), "text/vnd.graphviz"
    raise ValueError(f"unknown export format '{fmt}'; one of {', '.join(FORMATS)}")
