/** BPE tokenizer for Live mode (design doc §20), reading a repo's
 *  tokenizer.json directly. Two families cover the supported checkpoints:
 *
 *  - byte-level BPE (gpt2, SmolLM2): optional Digits pre-tokenizer, the GPT-2
 *    regex, bytes mapped through the printable-unicode table, merges per piece
 *  - sentencepiece-style BPE (TinyLLama-v0 and other llama tokenizers):
 *    normalize " "→"▁" with a prepended "▁", merge over the whole string,
 *    unknown characters fall back to <0xNN> byte tokens
 *
 *  Validated against Hugging Face `tokenizers` output in web/tests
 *  (fixtures generated by scripts/gen_live_fixtures.py).
 */

export interface TokenizerJSON {
  model: {
    type: string
    vocab: Record<string, number>
    merges: (string | [string, string])[]
    byte_fallback?: boolean
    unk_token?: string | null
  }
  normalizer?: unknown
  pre_tokenizer?: unknown
  added_tokens?: { id: number; content: string; special?: boolean }[]
}

export interface Tokenizer {
  encode(text: string): number[]
  /** full-sequence decode (safe across byte-fallback boundaries) */
  decode(ids: number[]): string
  /** display form of a single token ("▁the" → "·the", "Ġthe" → "·the") */
  pretty(id: number): string
  vocabSize: number
  bosId: number | null
  eosId: number | null
  addBos: boolean
}

// ---------------------------------------------------------- byte-level maps

function bytesToUnicode(): { enc: string[]; dec: Map<string, number> } {
  const bs: number[] = []
  for (let b = 33; b <= 126; b++) bs.push(b)
  for (let b = 161; b <= 172; b++) bs.push(b)
  for (let b = 174; b <= 255; b++) bs.push(b)
  const cs = [...bs]
  let n = 0
  for (let b = 0; b < 256; b++) {
    if (!bs.includes(b)) {
      bs.push(b)
      cs.push(256 + n)
      n++
    }
  }
  const enc = new Array<string>(256)
  const dec = new Map<string, number>()
  bs.forEach((b, i) => {
    const ch = String.fromCharCode(cs[i])
    enc[b] = ch
    dec.set(ch, b)
  })
  return { enc, dec }
}
const BYTE = bytesToUnicode()

// the GPT-2 pre-tokenization pattern
const GPT2_RE = /'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/gu

// ------------------------------------------------------------------- BPE

class BPE {
  ranks = new Map<string, number>()
  constructor(merges: (string | [string, string])[]) {
    merges.forEach((m, i) => {
      const key = typeof m === 'string' ? m : `${m[0]} ${m[1]}`
      this.ranks.set(key, i)
    })
  }

  merge(symbols: string[]): string[] {
    if (symbols.length < 2) return symbols
    const parts = [...symbols]
    for (;;) {
      let best = -1
      let bestRank = Infinity
      for (let i = 0; i < parts.length - 1; i++) {
        const r = this.ranks.get(`${parts[i]} ${parts[i + 1]}`)
        if (r !== undefined && r < bestRank) {
          bestRank = r
          best = i
        }
      }
      if (best === -1) return parts
      parts.splice(best, 2, parts[best] + parts[best + 1])
    }
  }
}

// -------------------------------------------------------------- factories

function findType(x: unknown, type: string): Record<string, unknown> | null {
  if (!x || typeof x !== 'object') return null
  const o = x as Record<string, unknown>
  if (o.type === type) return o
  for (const key of ['pretokenizers', 'normalizers', 'decoders']) {
    const seq = o[key]
    if (Array.isArray(seq)) {
      for (const item of seq) {
        const hit = findType(item, type)
        if (hit) return hit
      }
    }
  }
  return null
}

export function buildTokenizer(tj: TokenizerJSON, config?: { add_bos_token?: boolean }): Tokenizer {
  // older exports (gpt2) omit model.type; vocab+merges is BPE by construction
  if (tj.model.type !== 'BPE' && !(tj.model.type == null && tj.model.merges))
    throw new Error(`Live mode supports BPE tokenizers, not ${tj.model.type}`)
  const vocab = tj.model.vocab
  const idToTok = new Map<number, string>()
  for (const [t, i] of Object.entries(vocab)) idToTok.set(i, t)
  for (const a of tj.added_tokens ?? []) idToTok.set(a.id, a.content)
  const bpe = new BPE(tj.model.merges)
  const special = new Map((tj.added_tokens ?? []).map((a) => [a.content, a.id]))
  const bosId = special.get('<s>') ?? special.get('<|begin_of_text|>') ?? null
  const eosId = special.get('</s>') ?? special.get('<|endoftext|>') ?? special.get('<|end_of_text|>') ?? null

  const byteLevel = findType(tj.pre_tokenizer, 'ByteLevel') !== null
  const digits = findType(tj.pre_tokenizer, 'Digits') !== null
  const spStyle = !byteLevel && findType(tj.normalizer, 'Prepend') !== null
  const byteFallback = Boolean(tj.model.byte_fallback)
  const addBos = Boolean(config?.add_bos_token && bosId != null)
  const vocabSize = Math.max(...idToTok.keys()) + 1

  const encodePiece = (piece: string): number[] => {
    const merged = bpe.merge([...piece])
    const out: number[] = []
    for (const sym of merged) {
      const id = vocab[sym]
      if (id !== undefined) {
        out.push(id)
      } else if (byteFallback) {
        for (const b of new TextEncoder().encode(sym)) {
          const bid = vocab[`<0x${b.toString(16).toUpperCase().padStart(2, '0')}>`]
          if (bid !== undefined) out.push(bid)
        }
      }
      // no unk in these vocabularies: silently dropping is the tokenizers behavior
    }
    return out
  }

  const encode = (text: string): number[] => {
    const ids: number[] = []
    if (addBos && bosId != null) ids.push(bosId)
    if (spStyle) {
      const norm = ('▁' + text).replace(/ /g, '▁')
      ids.push(...encodePiece(norm))
      return ids
    }
    // byte-level: (Digits →) GPT-2 regex → byte map → BPE per piece
    const segments = digits ? text.split(/(\p{N})/u).filter((s) => s.length) : [text]
    for (const seg of segments) {
      for (const piece of seg.match(GPT2_RE) ?? []) {
        let mapped = ''
        for (const b of new TextEncoder().encode(piece)) mapped += BYTE.enc[b]
        ids.push(...encodePiece(mapped))
      }
    }
    return ids
  }

  const decode = (ids: number[]): string => {
    if (spStyle) {
      const bytes: number[] = []
      let first = true
      for (const id of ids) {
        const tok = idToTok.get(id) ?? ''
        if (special.has(tok) && (tj.added_tokens ?? []).find((a) => a.id === id)?.special) continue
        const bf = /^<0x([0-9A-Fa-f]{2})>$/.exec(tok)
        if (bf) {
          bytes.push(parseInt(bf[1], 16))
          continue
        }
        let s = tok.replace(/▁/g, ' ')
        if (first && s.startsWith(' ')) s = s.slice(1) // sentencepiece strips the prepended space
        first = false
        for (const b of new TextEncoder().encode(s)) bytes.push(b)
      }
      return new TextDecoder().decode(new Uint8Array(bytes))
    }
    const bytes: number[] = []
    for (const id of ids) {
      const tok = idToTok.get(id) ?? ''
      if (special.has(tok)) continue
      for (const ch of tok) {
        const b = BYTE.dec.get(ch)
        if (b !== undefined) bytes.push(b)
      }
    }
    return new TextDecoder().decode(new Uint8Array(bytes))
  }

  const pretty = (id: number): string => {
    const tok = idToTok.get(id) ?? `[${id}]`
    if (spStyle) {
      const bf = /^<0x([0-9A-Fa-f]{2})>$/.exec(tok)
      if (bf) {
        const b = parseInt(bf[1], 16)
        return b === 10 ? '⏎' : b === 9 ? '⇥' : tok
      }
      return tok.replace(/▁/g, '·')
    }
    let out = ''
    for (const ch of tok) {
      const b = BYTE.dec.get(ch)
      out += b === undefined ? ch : b === 32 ? '·' : b === 10 ? '⏎' : b >= 33 && b <= 126 ? String.fromCharCode(b) : '·'
    }
    // non-ascii utf8 pieces: show the decoded text when it is printable
    const asText = decode([id])
    return /^[\x20-\x7e]*$/.test(out) && out ? out : asText || out
  }

  return { encode, decode, pretty, vocabSize, bosId, eosId, addBos }
}
